name: dart_mp_analytics
description: A dart only package for wrapper around the Firebase Measurement Protocol API.
version: 1.0.0
repository: https://github.com/alvarobcprado/dart_mp_analytics
issue_tracker: https://github.com/alvarobcprado/dart_mp_analytics/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ">=1.1.0 <2.0.0"
  logger: ^2.2.0
  meta: ^1.15.0
  mocktail: ^1.0.3
  platform_info: ^4.0.2
  uuid: ^4.4.0

dev_dependencies:
  test: ^1.25.5
  very_good_analysis: ^5.1.0
