name: dart_mp_analytics
description: A dart only package for wrapper around the Firebase Measurement Protocol API.
version: 0.1.3
repository: https://github.com/alvarobcprado/dart_mp_analytics
issue_tracker: https://github.com/alvarobcprado/dart_mp_analytics/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ">=0.13.4 <2.0.0"
  logger: ^2.0.2+1
  meta: ^1.3.0
  mocktail: ^1.0.2
  platform_info: ^4.0.2
  uuid: ^4.3.1

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.1.0
