name: dart_mp_analytics
description: A dart only package for wrapper around the Firebase Measurement Protocol API.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.17.0

dependencies:
  http: ^0.13.4
  logger: ^1.4.0
  meta: ^1.3.0
  mocktail: ">=0.2.0 <0.4.0"
  platform_info: ^3.2.0
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
